### PR TITLE
Ignore extensions while not supported, fix misc

### LINKED ISSUE #11: panic: runtime error: index out of range in gaad.(*ADTS).excluded_channels
Hello.

I found a index out of range bug in gaad.

Please confirm.

Thanks.

reproduce code:
```
package gaad

import (
	"testing"
)

func TestFuzzCrashers(t *testing.T) {

	var crashers = []string{
		"\xff\xf10\xdc0\xb8\xad",
	}

	for _, f := range crashers {
		ParseADTS([]byte(f))
	}
}
```

Crash Log:
```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 17 [running]:
testing.tRunner.func1(0xc42004d5f0)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x5337a0, 0x5fbe10)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/Comcast/gaad.(*ADTS).excluded_channels(0xc42004d6c0, 0xc42009b301, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1832 +0x2ca
github.com/Comcast/gaad.(*ADTS).dynamic_range_info(0xc42004d6c0, 0x4, 0xb)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1787 +0x3f7
github.com/Comcast/gaad.(*ADTS).extension_payload(0xc42004d6c0, 0x2, 0x4f0006, 0x0, 0x0, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1731 +0x32b
github.com/Comcast/gaad.(*ADTS).fill_element(0xc42004d6c0, 0x6, 0x6, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1293 +0xbf
github.com/Comcast/gaad.(*ADTS).raw_data_block(0xc42004d6c0, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1020 +0x269
github.com/Comcast/gaad.(*ADTS).adts_frame(0xc42004d6c0, 0xc420019800, 0x7)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:796 +0x91
github.com/Comcast/gaad.ParseADTS(0xc4200b52a0, 0x7, 0x8, 0xc4200b52a0, 0x7, 0x8)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:773 +0xbe
github.com/Comcast/gaad.TestFuzzCrashers(0xc42004d5f0)
	/home/karas/go/src/github.com/Comcast/gaad/fuzzer_test.go:14 +0x90
testing.tRunner(0xc42004d5f0, 0x5647e0)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/Comcast/gaad	0.009s
```

### PR DESCRIPTION
**Pull request by LimitlessEarth**
Since we don't support extensions right now I would argue we should just omit them rather than approaching it with no intent to actually parse and use it. I'm running into situations where the parser will get tripped up in the bitstream and try to allocate gigs of memory. 

Additionally:
- excluded_channels.Additional_excluded_chns was never allocated resulting in a panic
- Add checks to not allocate the world elsewhere as well

### CODE REVIEW

File: aacsbrtables.go [hunk 1]
```diff
@@ -239,15 +241,23 @@ func freq_master(data *sbr_extension_data, k0 uint8, k2 uint8, bs_freq_scale uin
...
 	data.N_high = data.N_master - bs_xover_band
 	data.N_low = (data.N_high >> 1) + (data.N_high - (data.N_high>>1)<<1)
 
 	data.n = make([]uint8, 2)
 	data.n[0] = data.N_low
 	data.n[1] = data.N_high
 
+	// check for overflow or upper bounds
+	if data.N_high+bs_xover_band+1 < bs_xover_band || len(data.f_master) < int(data.N_high+bs_xover_band+1) {
+		return fmt.Errorf("f_tablehigh invalid index, likely malformed")
```
Comment (BlakeOrth) [inline aacsbrtables.go]: It seems like this would not only be easier to read this conditional, but also allow us to report a more informative error if we assign:
`index = data.N_high + bs_xover_band + 1`

File: aacsbrtables.go [hunk 2]
```diff
@@ -239,15 +241,23 @@ func freq_master(data *sbr_extension_data, k0 uint8, k2 uint8, bs_freq_scale uin
...
+	}
 	data.f_tablehigh = data.f_master[bs_xover_band : data.N_high+bs_xover_band+1]
+	// index out of range [255] with len 0
+	if len(data.f_tablehigh) < int(data.N_high) {
+		return fmt.Errorf("f_tablehigh invalid index, likely malformed")
```
Comment (BlakeOrth) [inline aacsbrtables.go]: Same here, this error could be more informative.

File: aacparser.go [hunk 3]
```diff
@@ -2128,25 +2147,37 @@ func (adts *ADTS) sbr_channel_pair_element(ext_data *sbr_extension_data, bs_amp_
...
-				}
-			}
-		}
 
-		e.Bs_fill_bits, _ = adts.reader.ReadBitsToByteArray(num_bits_left)
+		if num_bits_left > MaxBitsLeft {
+			return e, fmt.Errorf("Too many bits left, check bitstream continuity")
+		}
+
+		// TODO: Uncomment this when extensions are supported.
```
Comment (BlakeOrth) [inline aacparser.go]: egh no, just remove the non-functional code rather than comment it out. Commented out code is more of a liability than a benefit to future users/readers/implementers.

**Comment by BlakeOrth** [comment]
Does this resolve #11 ?

File: aacsbrtables.go (hunk 1 above)
Comment (LimitlessEarth) [reply aacsbrtables.go]: Is fix

**Comment by LimitlessEarth** [comment]
Yes it does

File: aacparser.go [hunk 4]
```diff
@@ -2020,6 +2032,10 @@ func (adts *ADTS) sbr_single_channel_element(ext_data *sbr_extension_data, bs_am
 		}
 
 		num_bits_left := cnt * 8
+		if num_bits_left > MaxBitsLeft {
+			return e, fmt.Errorf("Too many bits left, checl bitstream continuity")
```
Comment (laba2346) [inline aacparser.go]: `checl` -> `check`

**Review by laba2346 — APPROVED** [review]

File: aacsbrtables.go (hunk 2 above)
Comment (LimitlessEarth) [reply aacsbrtables.go]: Is fix

**Review by BlakeOrth — APPROVED** [review]
